FROM python:3.9

ENV PYTHONUNBUFFERED=1

########## for microsoft server ##########
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && apt-get install -y \
    unixodbc \
    unixodbc-dev \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18

RUN mkdir -p /lektore

WORKDIR  /lektore

COPY requirements.txt /lektore/requirements.txt

COPY ./lektore /lektore

RUN pip install -r /lektore/requirements.txt

COPY ./entrypoint.sh /lektore/entrypoint.sh
CMD ["sh", "/lektore/entrypoint.sh"]

