version: '3'
services:
  lektore-app:
    build:
      context: .
      dockerfile: ./DockerFile
    volumes:
      - .:/lektore
    ports:
      - 8000:8000
    image: lektore-app:lektore
    container_name: lektore_container
    command:
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}