FROM python:3.10

ENV PYTHONUNBUFFERED=1

RUN mkdir -p /lektore

WORKDIR  /lektore

COPY requirements.txt /lektore/requirements.txt

COPY ./lektore /lektore

RUN pip install -r /lektore/requirements.txt

COPY ./entrypoint.sh /lektore/entrypoint.sh
CMD ["sh", "/lektore/entrypoint.sh"]

