version: '3'
services:
  lektore-app:
    build:
      context: .
      dockerfile: ./DockerFile
    volumes:
      - .:/lektore
    expose:
      - "8000"
    image: lektore-app:lektore
    container_name: lektore-api
#    command:
#      sh -c "python manage.py collectstatic --no-input &&ls&& gunicorn lektore.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - lektore-redis
    environment:
      - DJANGO_SETTINGS_MODULE=lektore.settings
      - DB_NAME=lektore
      - DB_USER=lektoreadmin
      - DB_PASSWORD=@50324435BH
      - DB_HOST=lektore.database.windows.net
      - DB_PORT=1433
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  lektore-redis:
    image: redis:alpine
    container_name: lektore-redis
  nginx:
    image: nginx:alpine
    container_name: lektore-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/lektore/static
    depends_on:
      - lektore-app