# Generated by Django 3.2.16 on 2022-12-20 13:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=25, unique=True)),
                ('course_duration', models.FloatField(default=0, verbose_name='Course Duration in hours')),
                ('course_category', models.CharField(choices=[('ielts', 'IELTS'), ('elocution', 'Elocution'), ('other', 'Other')], max_length=50)),
                ('course_type', models.CharField(choices=[('live', 'Live'), ('other', 'Other')], max_length=50)),
                ('course_rate', models.CharField(choices=[('hr', '/hr'), ('total', 'total')], max_length=10)),
                ('course_price', models.CharField(max_length=10)),
                ('course_description', models.TextField()),
                ('course_goal', models.TextField()),
                ('intro_video', models.URLField(verbose_name='Link to video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserVerificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('otp_is_verified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary')], max_length=15, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('tutor_id', models.CharField(max_length=10, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_qualified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary')], max_length=15, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', '1-3 Years'), ('novice', '3-5 Years'), ('advanced', '5-10 Years'), ('expert', '10+ Years')], max_length=100, null=True)),
                ('service', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ielts', 'IELTS'), ('learn-english', 'Learn English Language'), ('business-language', 'Business English Language'), ('elocution', 'Elocution')], max_length=100), blank=True, default=list, null=True, size=None)),
                ('is_qualified', models.BooleanField(default=False)),
                ('from_destination', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('to_destination', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(max_length=256)),
                ('module_description', models.TextField()),
                ('module_duration', models.FloatField(default=0)),
                ('module_video', models.URLField(verbose_name='Link to module video')),
                ('module_pdf', models.URLField(verbose_name='Link to module pdf')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutorprofile'),
        ),
    ]
