# Generated by Django 4.1.4 on 2022-12-12 22:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary')], max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_qualified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary')], max_length=15)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', '1-3 Years'), ('novice', '3-5 Years'), ('advanced', '5-10 Years'), ('expert', '10+ Years')], max_length=100, null=True)),
                ('service', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ielts', 'IELTS'), ('learn-english', 'Learn English Language'), ('business-language', 'Business English Language'), ('elocution', 'Elocution')], max_length=100), blank=True, default=list, null=True, size=None)),
                ('is_qualified', models.BooleanField(default=False)),
                ('from_destination', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('to_destination', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
