# Generated by Django 4.1.4 on 2022-12-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tuteeprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuteeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tuteeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
