# Generated by Django 4.2 on 2024-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoroom',
            name='online_users',
            field=models.ManyToManyField(blank=True, to='app.tuteeprofile', verbose_name='Invited Users'),
        ),
    ]
