# Generated by Django 4.2 on 2024-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240131_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TuteeOrder',
            new_name='CourseOrder',
        ),
        migrations.RenameModel(
            old_name='RegisteredTuteeCourse',
            new_name='TuteeProgress',
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='app.course'),
        ),
    ]
