# Generated by Django 4.2 on 2024-06-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_videoroom_online_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='course_tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_courses', to='app.tutorprofile'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='dashboard_wallpaper',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.tutorprofile'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='app.wallet'),
        ),
    ]
