# Generated by Django 3.2.16 on 2023-02-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_availability_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteeprofile',
            name='tutee_id',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
