# Generated by Django 3.2.16 on 2023-02-26 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20230214_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteeprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tuteeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tutee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('highest_qualification', models.CharField(choices=[('PhD', 'Doctor of Philosophy'), ('MD', 'Doctor of Medicine'), ('JD', 'Juris Doctor'), ('MBA', 'Master of Business Administration'), ('MFA', 'Master of Fine Arts'), ('MA', 'Master of Arts'), ('MSc', 'Master of Science'), ('MEd', 'Master of Education'), ('LLB', 'Bachelor of Laws'), ('BA', 'Bachelor of Arts'), ('BSc', 'Bachelor of Science'), ('BEd', 'Bachelor of Education'), ('BSN', 'Bachelor of Science in Nursing'), ('BFA', 'Bachelor of Fine Arts'), ('BBA', 'Bachelor of Business Administration'), ('AA', 'Associate of Arts'), ('AS', 'Associate of Science'), ('AAS', 'Associate of Applied Science'), ('Certificate', 'Certificate')], max_length=100)),
                ('previous_age_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Previous Age Group Taught')),
                ('current_age_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Age Group Able to Teach')),
                ('teaching_experience', models.TextField(blank=True, null=True)),
                ('subjects_taught', models.TextField(blank=True, null=True)),
                ('qualified', models.BooleanField(default=False)),
                ('aspirations', models.TextField(blank=True, null=True)),
                ('remote_teaching', models.BooleanField(default=False)),
                ('intro_video', models.CharField(blank=True, max_length=255, null=True)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to='app.tutorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
