# Generated by Django 4.2 on 2024-02-11 21:07

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tuteeprogress_module_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuteeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('ielts', 'IELTS'), ('learn english', 'Learn English'), ('elocution', ''), ('Business english language', 'Business English')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tuteeprofile',
            name='from_destination',
        ),
        migrations.RemoveField(
            model_name='tuteeprofile',
            name='to_destination',
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='is_refugee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='moving_from',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='moving_to',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='services',
            field=models.ManyToManyField(to='app.tuteeservice'),
        ),
    ]
