# Generated by Django 3.2.16 on 2023-03-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230226_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalqualification',
            name='certification_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalqualification',
            name='tutor_resume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
