# Generated by Django 3.2.16 on 2023-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230301_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteeprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
