# Generated by Django 3.2.16 on 2023-12-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20231201_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='tutee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tutee_course_class', to='app.tuteeprofile'),
        ),
    ]
