# Generated by Django 3.2.16 on 2023-12-06 11:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20231206_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1888-08-08', null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1888-08-08', null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='tutee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutee_course_class', to='app.tuteeprofile'),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='current_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='current_state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='current_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='current_state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
