# Generated by Django 3.2.16 on 2023-12-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20231206_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_goal',
            new_name='course_overview',
        ),
        migrations.RenameField(
            model_name='courseorder',
            old_name='status',
            new_name='purchase_status',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='completion_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='last_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_audio',
            field=models.URLField(default=' ', verbose_name='Link to module audio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='module_completion_level',
            field=models.JSONField(null=True, verbose_name='completed tasks'),
        ),
        migrations.AlterField(
            model_name='courseorder',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_orders', to='app.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='app.course'),
        ),
    ]
