# Generated by Django 3.2.16 on 2023-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20231207_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_audio',
            field=models.URLField(null=True, verbose_name='Link to module audio'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_video',
            field=models.URLField(null=True, verbose_name='Link to module video'),
        ),
    ]
