# Generated by Django 4.1 on 2023-12-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20231207_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='completion_level',
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_completion_level',
        ),
        migrations.AddField(
            model_name='module',
            name='is_module_audio_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='is_module_pdf_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='is_module_video_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_id'], name='app_course_course__68a68e_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['tutor_id'], name='app_tutorpr_tutor_i_e0911e_idx'),
        ),
    ]
