# Generated by Django 4.1 on 2024-01-08 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_communitypost_postappraisal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredTuteeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_module_video_completed', models.BooleanField(default=False)),
                ('is_module_audio_completed', models.BooleanField(default=False)),
                ('is_module_pdf_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_tutees', to='app.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuteeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('purchase_status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutee_orders', to='app.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='courseorder',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseorder',
            name='tutee',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_module_audio_completed',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_module_pdf_completed',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_module_video_completed',
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='last_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='CourseOrder',
        ),
        migrations.AddField(
            model_name='tuteeorder',
            name='tutee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tuteeprofile'),
        ),
        migrations.AddField(
            model_name='registeredtuteecourse',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutee_course_modules', to='app.module'),
        ),
        migrations.AddField(
            model_name='registeredtuteecourse',
            name='tutee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_courses', to='app.tuteeprofile'),
        ),
    ]
